#!/usr/bin/env python3
"""Generate C conformance vectors for ignirelay-field-node (B6).

Single source of truth = the frozen App contracts:
  - LORA-WIRE frames   -> IgniRelay/docs/specs/lora_wire_v1_vectors.json
  - EventEnvelope v3   -> IgniRelay/docs/specs/wire_conformance_v1.json
                          (envelope_samples, BLE-ingest subset only)

This generator INVENTS NO contract and REGENERATES NO corpus. Every expected
value (frame bytes, mac8, crc16, drop_reason; canonical_sig_input, signature,
field_mac, payload_sha256, keys) is copied **verbatim** from the App JSON. The
one thing it computes is the *encoded* `EventEnvelopeV2` protobuf used as decoder
**input**, produced by the lab B2 reference codec (`ignirelay_lab.wire.envelope_v3`,
proven byte-for-byte against the same corpus's canonical/signature in
`tests/test_envelope_v3_conformance.py`). The C test's correctness is anchored to
the corpus expected canonical/signature/field_mac, not to this encoding.

Outputs (marked GENERATED — do not hand-edit) into the field-node repo:
  - tests/wire/lora_vectors.inc       (§3-§8 LORA-WIRE frames: 51 positive + 11 negative)
  - tests/wire/envelope_vectors.inc   (envelope BLE-ingest subset: event_type in {1,50})

App-dir / field-node-dir resolution mirrors the lab tests:
  IGNIRELAY_APP_DIR        overrides the App repo root (default ../IgniRelay)
  IGNIRELAY_FIELD_NODE_DIR overrides the firmware repo root (default ../ignirelay-field-node)

Usage:
    python -m tools.gen_c_vectors            # write the .inc files
    python -m tools.gen_c_vectors --check    # fail if outputs would change (CI)
"""

from __future__ import annotations

import argparse
import io
import json
import os
import sys
from pathlib import Path

# Allow running as a script (python tools/gen_c_vectors.py) or as a module.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ignirelay_lab.wire.envelope_v3 import (  # noqa: E402
    EventEnvelopeV2,
    HazardMarkerData,
    HlcTimestamp,
    StatusUpdateData,
    lcg_payload,
)

# EventTypeV2 values whose typed payload the Node translates to a §5 LoRa compact
# payload during BLE ingest. The corpus only carries STATUS_UPDATE(1) and
# HAZARD(50) among these (no PRESENCE(3)/CHECKPOINT(4) envelope samples exist);
# we extract exactly what the corpus provides and fabricate nothing.
INGEST_EVENT_TYPES = (1, 50)


def _app_dir() -> Path:
    override = os.environ.get("IGNIRELAY_APP_DIR")
    if override:
        return Path(override)
    return Path(__file__).resolve().parents[2] / "IgniRelay"


def _field_node_dir() -> Path:
    override = os.environ.get("IGNIRELAY_FIELD_NODE_DIR")
    if override:
        return Path(override)
    return Path(__file__).resolve().parents[2] / "ignirelay-field-node"


def _load_json(path: Path) -> dict:
    if not path.is_file():
        raise SystemExit(
            f"missing App contract: {path}\n"
            f"(set IGNIRELAY_APP_DIR to the App repo root)"
        )
    return json.load(io.open(path, encoding="utf-8"))


# ── C emission helpers ────────────────────────────────────────────────────────
def _c_bytes(name: str, data: bytes) -> str:
    body = ", ".join(f"0x{b:02x}" for b in data)
    return f"static const uint8_t {name}[] = {{ {body} }};"


def _c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


HEADER = (
    "/* GENERATED by ignirelay-lab/tools/gen_c_vectors.py — DO NOT EDIT BY HAND.\n"
    " * Source of truth: App repo {src} (spec_rev {rev}).\n"
    " * Regenerate with `python -m tools.gen_c_vectors` from the lab repo.\n"
    " * Every expected value is copied verbatim from the frozen App contract;\n"
    " * this file is a build artifact, not a contract. */\n"
)


# ── LORA-WIRE frame vectors ───────────────────────────────────────────────────
def build_lora_inc(vectors: dict) -> str:
    meta = vectors["meta"]
    tf = vectors["test_field"]
    rev = meta["spec_rev"]

    out: list[str] = []
    out.append(HEADER.format(src="docs/specs/lora_wire_v1_vectors.json", rev=rev))
    out.append("#ifndef IGNIRELAY_GEN_LORA_VECTORS_INC")
    out.append("#define IGNIRELAY_GEN_LORA_VECTORS_INC")
    out.append("")
    out.append("#include <stddef.h>")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f'#define IR_GEN_LORA_SPEC_REV {_c_str(rev)}')
    secret = bytes.fromhex(tf["field_join_secret_hex"])
    out.append(_c_bytes("ir_gen_lora_field_join_secret", secret))
    out.append(f"#define IR_GEN_LORA_FIELD_JOIN_SECRET_LEN {len(secret)}")
    out.append(_c_bytes("ir_gen_lora_mac_key", bytes.fromhex(tf["lora_mac_key_hex"])))
    out.append(_c_bytes("ir_gen_lora_field_id", bytes.fromhex(tf["field_id_hex"])))
    out.append(_c_bytes("ir_gen_lora_field_tag", bytes.fromhex(tf["field_tag_hex"])))
    out.append("")
    st = meta["crc16_self_test"]
    out.append(f'#define IR_GEN_LORA_CRC_SELFTEST_INPUT {_c_str(st["input_ascii"])}')
    out.append(f'#define IR_GEN_LORA_CRC_SELFTEST_EXPECTED 0x{st["expected_hex"]}')
    out.append("")

    # Positive frames
    out.append("struct ir_gen_lora_pos {")
    out.append("    const char *name;")
    out.append("    const uint8_t *frame; size_t frame_len;")
    out.append("    uint8_t is_event;")
    out.append("    uint8_t flags; uint16_t src_node; uint16_t packet_seq; uint8_t ttl;")
    out.append("    const uint8_t *event_id; uint8_t event_type; uint8_t priority;")
    out.append("    uint64_t hlc_ms; uint16_t hlc_counter;")
    out.append("    const uint8_t *payload; size_t payload_len;")
    out.append("    uint16_t ack_seq; const uint8_t *event_id_prefix; uint8_t status;")
    out.append("};")
    out.append("")

    rows: list[str] = []
    for i, f in enumerate(vectors["frames"]):
        frame = bytes.fromhex(f["frame_hex"])
        out.append(_c_bytes(f"lp{i}_frame", frame))
        is_event = 1 if f["ptype"] == 1 else 0
        eid_ref = "NULL"
        pl_ref = "NULL"
        prefix_ref = "NULL"
        if is_event:
            out.append(_c_bytes(f"lp{i}_eid", bytes.fromhex(f["event_id_hex"])))
            out.append(_c_bytes(f"lp{i}_pl", bytes.fromhex(f["payload_hex"])))
            eid_ref = f"lp{i}_eid"
            pl_ref = f"lp{i}_pl"
        else:
            out.append(
                _c_bytes(f"lp{i}_prefix", bytes.fromhex(f["event_id_prefix_hex"]))
            )
            prefix_ref = f"lp{i}_prefix"
        rows.append(
            "    { .name=%s, .frame=lp%d_frame, .frame_len=%d, .is_event=%d,"
            " .flags=%d, .src_node=%d, .packet_seq=%d, .ttl=%d,"
            " .event_id=%s, .event_type=%d, .priority=%d, .hlc_ms=%dULL,"
            " .hlc_counter=%d, .payload=%s, .payload_len=%d,"
            " .ack_seq=%d, .event_id_prefix=%s, .status=%d },"
            % (
                _c_str(f["name"]), i, len(frame), is_event,
                f.get("flags", 0), f["src_node"], f["packet_seq"], f["ttl"],
                eid_ref, f.get("event_type", 0) or 0, f.get("priority", 0) or 0,
                f.get("hlc_ms", 0) or 0, f.get("hlc_counter", 0) or 0,
                pl_ref, f.get("payload_len", 0) or 0,
                f.get("ack_seq", 0) or 0, prefix_ref, f.get("status", 0) or 0,
            )
        )
    out.append("static const struct ir_gen_lora_pos ir_gen_lora_pos[] = {")
    out.extend(rows)
    out.append("};")
    out.append(
        "#define IR_GEN_LORA_POS_COUNT "
        "(sizeof(ir_gen_lora_pos) / sizeof(ir_gen_lora_pos[0]))"
    )
    out.append("")

    # Negative frames
    out.append("struct ir_gen_lora_neg {")
    out.append("    const char *name;")
    out.append("    const uint8_t *frame; size_t frame_len;")
    out.append("    const char *expect_reason;")
    out.append("    uint8_t has_local_est; uint64_t local_est_ms;")
    out.append("    const uint8_t *precondition_seen_event_id;")
    out.append("};")
    out.append("")
    nrows: list[str] = []
    for i, n in enumerate(vectors["negative"]):
        frame = bytes.fromhex(n["frame_hex"])
        out.append(_c_bytes(f"ln{i}_frame", frame))
        seen_ref = "NULL"
        if n.get("precondition_seen_event_id_hex"):
            out.append(
                _c_bytes(
                    f"ln{i}_seen",
                    bytes.fromhex(n["precondition_seen_event_id_hex"]),
                )
            )
            seen_ref = f"ln{i}_seen"
        has_le = 1 if "local_est_ms" in n else 0
        le = n.get("local_est_ms", 0)
        nrows.append(
            "    { .name=%s, .frame=ln%d_frame, .frame_len=%d, .expect_reason=%s,"
            " .has_local_est=%d, .local_est_ms=%dULL,"
            " .precondition_seen_event_id=%s },"
            % (
                _c_str(n["name"]), i, len(frame), _c_str(n["expect_reason"]),
                has_le, le, seen_ref,
            )
        )
    out.append("static const struct ir_gen_lora_neg ir_gen_lora_neg[] = {")
    out.extend(nrows)
    out.append("};")
    out.append(
        "#define IR_GEN_LORA_NEG_COUNT "
        "(sizeof(ir_gen_lora_neg) / sizeof(ir_gen_lora_neg[0]))"
    )
    out.append("")
    out.append("#endif /* IGNIRELAY_GEN_LORA_VECTORS_INC */")
    out.append("")
    return "\n".join(out)


# ── EventEnvelope v3 BLE-ingest subset ────────────────────────────────────────
def _payload_bytes(es: dict) -> bytes:
    """Reconstruct the inner typed payload: inline hex, or the corpus LCG."""
    if "payload_hex" in es:
        return bytes.fromhex(es["payload_hex"])
    g = es["payload_generator"]
    if g["algorithm"] != "lcg_byte_pattern_v1":
        raise SystemExit(f"unknown payload_generator: {g['algorithm']}")
    return lcg_payload(g["seed"], g["size"])


def _is_typed(es: dict, payload: bytes) -> bool:
    """A payload is 'typed' iff it decodes to its §5 struct AND re-encodes to the
    identical bytes (procedural/random LCG payloads do not). Only typed payloads
    are translated to a compact LoRa payload in the C ingest ztest."""
    cls = StatusUpdateData if es["event_type"] == 1 else HazardMarkerData
    try:
        return cls.decode(payload).encode() == payload
    except Exception:
        return False


def _envelope_from_struct(es: dict, payload: bytes, signature: bytes) -> EventEnvelopeV2:
    return EventEnvelopeV2(
        protocol_version=es["protocol_version"],
        envelope_id=bytes.fromhex(es["envelope_id_hex"]),
        event_type=es["event_type"],
        priority=es["priority"],
        created_at_hlc=HlcTimestamp(
            ms=es["created_at_hlc"]["ms_since_epoch"],
            counter=es["created_at_hlc"]["counter"],
        ),
        expires_at_hlc=HlcTimestamp(
            ms=es["expires_at_hlc"]["ms_since_epoch"],
            counter=es["expires_at_hlc"]["counter"],
        ),
        author_key=bytes.fromhex(es["author_key_hex"]),
        sig_algo=es["sig_algo"],
        signature=signature,
        payload=payload,
        max_hops=es["max_hops"],
        last_relay_id="",
        is_experimental=es["is_experimental"],
        field_id=bytes.fromhex(es["field_id_hex"]),
        field_mac=bytes.fromhex(es["field_mac_hex"]),
    )


def build_envelope_inc(corpus: dict) -> str:
    tf = corpus["test_field"]
    rev = corpus["corpus_revision"]
    samples = [
        s
        for s in corpus["envelope_samples"]
        if s["envelope_struct"]["event_type"] in INGEST_EVENT_TYPES
    ]
    samples.sort(key=lambda s: (s["envelope_struct"]["event_type"], s["name"]))

    out: list[str] = []
    out.append(HEADER.format(src="docs/specs/wire_conformance_v1.json", rev=rev))
    out.append("#ifndef IGNIRELAY_GEN_ENVELOPE_VECTORS_INC")
    out.append("#define IGNIRELAY_GEN_ENVELOPE_VECTORS_INC")
    out.append("")
    out.append("#include <stddef.h>")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f'#define IR_GEN_ENV_CORPUS_REV {_c_str(rev)}')
    secret = bytes.fromhex(tf["field_join_secret_hex"])
    out.append(_c_bytes("ir_gen_env_field_join_secret", secret))
    out.append(f"#define IR_GEN_ENV_FIELD_JOIN_SECRET_LEN {len(secret)}")
    out.append(_c_bytes("ir_gen_env_field_mac_key", bytes.fromhex(tf["field_mac_key_hex"])))
    out.append(_c_bytes("ir_gen_env_field_id", bytes.fromhex(tf["field_id_hex"])))
    out.append("")

    # ── Group B — canonical-encoder + field_mac matrix (ALL subset samples) ────
    # The Node recomputes the 141-B canonical_sig_input from the envelope fields
    # and the field_mac=HMAC(field_mac_key, canonical)[0..15]. These cover the
    # whole type×priority×size matrix the corpus carries for {1,50}, including the
    # 23 samples that carry no Ed25519 signature.
    out.append("struct ir_gen_env_canon {")
    out.append("    const char *name; uint32_t protocol_version;")
    out.append("    const uint8_t *envelope_id; const uint8_t *field_id;")
    out.append("    uint32_t event_type; uint32_t priority;")
    out.append("    uint64_t created_ms; uint32_t created_counter;")
    out.append("    uint64_t expires_ms; uint32_t expires_counter;")
    out.append("    uint32_t max_hops; const uint8_t *author_key; uint8_t sig_algo;")
    out.append("    const uint8_t *payload_sha256;")
    out.append("    const uint8_t *canonical; size_t canonical_len;")
    out.append("    const uint8_t *field_mac;")
    out.append("};")
    out.append("")
    crows: list[str] = []
    for i, s in enumerate(samples):
        es = s["envelope_struct"]
        out.append(_c_bytes(f"ec{i}_eid", bytes.fromhex(es["envelope_id_hex"])))
        out.append(_c_bytes(f"ec{i}_fid", bytes.fromhex(es["field_id_hex"])))
        out.append(_c_bytes(f"ec{i}_ak", bytes.fromhex(es["author_key_hex"])))
        out.append(_c_bytes(f"ec{i}_sha", bytes.fromhex(s["payload_sha256_hex"])))
        canonical = bytes.fromhex(s["expected_canonical_sig_input_hex"])
        out.append(_c_bytes(f"ec{i}_can", canonical))
        out.append(_c_bytes(f"ec{i}_fm", bytes.fromhex(es["field_mac_hex"])))
        crows.append(
            "    { .name=%s, .protocol_version=%d, .envelope_id=ec%d_eid,"
            " .field_id=ec%d_fid, .event_type=%d, .priority=%d, .created_ms=%dULL,"
            " .created_counter=%d, .expires_ms=%dULL, .expires_counter=%d,"
            " .max_hops=%d, .author_key=ec%d_ak, .sig_algo=%d,"
            " .payload_sha256=ec%d_sha, .canonical=ec%d_can, .canonical_len=%d,"
            " .field_mac=ec%d_fm },"
            % (
                _c_str(s["name"]), es["protocol_version"], i, i,
                es["event_type"], es["priority"],
                es["created_at_hlc"]["ms_since_epoch"], es["created_at_hlc"]["counter"],
                es["expires_at_hlc"]["ms_since_epoch"], es["expires_at_hlc"]["counter"],
                es["max_hops"], i, es["sig_algo"], i, i, len(canonical), i,
            )
        )
    out.append("static const struct ir_gen_env_canon ir_gen_env_canon[] = {")
    out.extend(crows)
    out.append("};")
    out.append(
        "#define IR_GEN_ENV_CANON_COUNT "
        "(sizeof(ir_gen_env_canon) / sizeof(ir_gen_env_canon[0]))"
    )
    out.append("")

    # ── Group A — full BLE-ingest pipeline (only fully-signed samples) ─────────
    # A real EventEnvelopeV2 has a 64-B Ed25519 signature, so only the signed
    # samples can be decoded as complete envelopes. For each: proto decode →
    # SHA-256(payload) → recompute canonical → Ed25519 verify → field_mac verify
    # → translate typed payload to §5 compact (when `typed`).
    out.append("struct ir_gen_env_full {")
    out.append("    const char *name; uint8_t event_type; uint8_t priority;")
    out.append("    const uint8_t *envelope; size_t envelope_len;")
    out.append("    const uint8_t *payload; size_t payload_len;")
    out.append("    const uint8_t *payload_sha256;")
    out.append("    const uint8_t *canonical; size_t canonical_len;")
    out.append("    const uint8_t *signature;          /* 64 B */")
    out.append("    const uint8_t *field_mac;          /* 16 B */")
    out.append("    uint8_t typed;                     /* 1 => translate to compact */")
    out.append("};")
    out.append("")
    frows: list[str] = []
    n_signed = 0
    n_typed = 0
    for s in samples:
        sig_hex = s.get("expected_signature_hex")
        if not sig_hex:
            continue
        es = s["envelope_struct"]
        i = n_signed
        signature = bytes.fromhex(sig_hex)
        payload = _payload_bytes(es)
        typed = _is_typed(es, payload)
        env = _envelope_from_struct(es, payload, signature).encode()
        canonical = bytes.fromhex(s["expected_canonical_sig_input_hex"])
        out.append(_c_bytes(f"ef{i}_env", env))
        out.append(_c_bytes(f"ef{i}_pl", payload))
        out.append(_c_bytes(f"ef{i}_sha", bytes.fromhex(s["payload_sha256_hex"])))
        out.append(_c_bytes(f"ef{i}_can", canonical))
        out.append(_c_bytes(f"ef{i}_sig", signature))
        out.append(_c_bytes(f"ef{i}_fm", bytes.fromhex(es["field_mac_hex"])))
        frows.append(
            "    { .name=%s, .event_type=%d, .priority=%d, .envelope=ef%d_env,"
            " .envelope_len=%d, .payload=ef%d_pl, .payload_len=%d,"
            " .payload_sha256=ef%d_sha, .canonical=ef%d_can, .canonical_len=%d,"
            " .signature=ef%d_sig, .field_mac=ef%d_fm, .typed=%d },"
            % (
                _c_str(s["name"]), es["event_type"], es["priority"], i, len(env),
                i, len(payload), i, i, len(canonical), i, i, 1 if typed else 0,
            )
        )
        n_signed += 1
        if typed:
            n_typed += 1
    out.append("static const struct ir_gen_env_full ir_gen_env_full[] = {")
    out.extend(frows)
    out.append("};")
    out.append(
        "#define IR_GEN_ENV_FULL_COUNT "
        "(sizeof(ir_gen_env_full) / sizeof(ir_gen_env_full[0]))"
    )
    out.append(f"#define IR_GEN_ENV_TYPED_COUNT {n_typed}")
    out.append("")
    out.append("#endif /* IGNIRELAY_GEN_ENVELOPE_VECTORS_INC */")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate field-node C conformance vectors")
    ap.add_argument(
        "--check",
        action="store_true",
        help="fail (exit 2) if the generated outputs differ from on-disk",
    )
    args = ap.parse_args()

    app = _app_dir()
    lora = _load_json(app / "docs" / "specs" / "lora_wire_v1_vectors.json")
    corpus = _load_json(app / "docs" / "specs" / "wire_conformance_v1.json")

    out_dir = _field_node_dir() / "tests" / "wire"
    targets = {
        out_dir / "lora_vectors.inc": build_lora_inc(lora),
        out_dir / "envelope_vectors.inc": build_envelope_inc(corpus),
    }

    n_pos = len(lora["frames"])
    n_neg = len(lora["negative"])
    n_env = sum(
        1
        for s in corpus["envelope_samples"]
        if s["envelope_struct"]["event_type"] in INGEST_EVENT_TYPES
    )

    if args.check:
        drift = False
        for path, content in targets.items():
            existing = path.read_text(encoding="utf-8") if path.is_file() else None
            if existing != content:
                print(f"[gen_c_vectors] DRIFT: {path}")
                drift = True
        if drift:
            print("[gen_c_vectors] outputs are stale — rerun without --check")
            return 2
        print(
            f"[gen_c_vectors] --check OK "
            f"(lora {n_pos}+{n_neg}, envelope subset {n_env})"
        )
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    for path, content in targets.items():
        path.write_text(content, encoding="utf-8")
        print(f"[gen_c_vectors] wrote {path}")
    print(
        f"[gen_c_vectors] lora positive={n_pos} negative={n_neg}; "
        f"envelope BLE-ingest subset (event_type in {INGEST_EVENT_TYPES})={n_env}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
